import type {Metadata} from 'next';
import {Toaster} from '@/components/ui/toaster';
import './globals.css';
import { AppLayout } from '@/layouts/app-layout';
import { Kantumruy_Pro } from 'next/font/google';

const kantumruy = Kantumruy_Pro({ subsets: ['latin', 'khmer'] });

export const metadata: Metadata = {
  title: 'VoiceScribe',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kantumruy.className} antialiased`}>
        <AppLayout>
          {children}
        </AppLayout>
        <Toaster />
      </body>
    </html>
  );
}
